Repository kalviumcommunity/S70_keerthan_capstone_Solevault, pull requests merged in 2025-06, with the labels that each got.

#14 feat: Implement email OTP verification for signup and rate limiting
  Solevault/.gitignore
  Solevault/src/pages/SignUp.jsx
  backend/index.js
  backend/models/PreVerificationUser.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
Labels: Review effort 3/5

#16 added the baout page
  Solevault/src/App.jsx
  Solevault/src/pages/AboutPage.jsx
Labels: Review effort 2/5

#17 Cookie policy
  Solevault/src/App.jsx
  Solevault/src/components/layout/Footer.jsx
  Solevault/src/pages/CookiePolicyPage.jsx
Labels: Review effort 2/5

#19 privacy policy page added
  Solevault/src/App.jsx
  Solevault/src/pages/PrivacyPolicyPage.jsx
Labels: Review effort 2/5

#22 tested 5 units using vitest
  Solevault/package-lock.json
  Solevault/package.json
  Solevault/src/index.css
  Solevault/src/pages/AboutPage.jsx
  Solevault/src/pages/PrivacyPolicyPage.jsx
  Solevault/src/tests/Components.test.jsx
  Solevault/src/tests/setup.js
  Solevault/vite.config.js
Labels: Review effort 3/5

#23 feat: Add Dockerfile for backend service
  backend/Dockerfile
  package-lock.json
  package.json
Labels: Review effort 2/5, Possible security concern

#24 added google auth and forgot password
  Solevault/src/App.jsx
  Solevault/src/pages/ForgotPasswordPage.jsx
  Solevault/src/pages/ResetPasswordPage.jsx
  Solevault/src/pages/SignIn.jsx
  Solevault/src/pages/SignUp.jsx
  Solevault/src/services/sneakerService.jsx
  backend/.dockerignore
  backend/Dockerfile
  backend/models/User.js
  backend/routes/auth.js
Labels: Review effort 4/5, Possible security concern

#25 implemented langchain in ai autocomplete
  backend/package-lock.json
  backend/package.json
  backend/routes/aiRoutes.js
Labels: Review effort 3/5

#26 added websocket connection
  Solevault/src/components/community/LiveCommentFeed.jsx
  Solevault/src/pages/Community.jsx
  Solevault/src/pages/Dashboard.jsx
  backend/index.js
  backend/package-lock.json
  backend/package.json
Labels: Review effort 3/5, Possible security concern

#27 added cron-job for market values
  backend/index.js
  backend/package-lock.json
  backend/package.json
Labels: Review effort 2/5
